---
- hosts: all
  become: yes
  tasks:
          - name: Download kubeadm and its dependiences
            get_url: 
              url: http://files.cloudthat.training/devops/kubernetes-ckad/kubeadm-script-v1.18.sh
              dest: /home/ubuntu/kubeadm-script-v1.18.sh
              
          - name: Run the bash script
            become: yes
            become_user: root
            shell: bash /home/ubuntu/kubeadm-script-v1.18.s 

          - name: Start the cluster
            become: yes
            become_user: root
            command: "kubeadm init"
 
          - name: create .kube directory
            become: yes
            become_user: ubuntu
            file:
              path: $HOME/.kube
              state: directory
              mode: 0777

          - name: providing it network
            shell: sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config && export kubever=$(kubectl version | base64 | tr -d '\n') && kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever"
            register: out

          - name: listing the control plane pods
            shell: kubectl get pods --namespace=kube-system --kubeconfig=/home/ubuntu/.kube/config

          - name: listing the the nodes
            shell: kubectl get nodes --namespace=kube-system --kubeconfig=/home/ubuntu/.kube/config
          
          - name: unitainting the master node
            shell: kubectl taint nodes --all node-role.kubernetes.io/master-

          - name: Transfer kube config file kubeadm to Jenkins
            synchronize:
              src: $HOME/.kube/config
              dest: $HOME/.kube/config
            delegate_to: kubeadm-node

